import { Request, Response } from "express";
import asyncHandler from "express-async-handler";

export default asyncHandler(async (req: Request, res: Response) => {
	const articleId = req.params.id;

	// For now, return a placeholder summary
	const summary = `This is a summary for article with ID: ${articleId}. This is a placeholder summary generated by the backend.`;

	res.json({ summary });
});
